networks:
  subrede_esquerda:
    ipam:
      config:
        - subnet: 192.168.120.0/24
  subrede_direita:
    ipam:
      config:
        - subnet: 192.168.130.0/24
  rede_controle:
    ipam:
      config:
        - subnet: 192.168.140.0/24

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - subrede_esquerda
      - subrede_direita
      - rede_controle

  sensor_a:
    build: 
      context: .
      dockerfile: Dockerfile.sensor
    container_name: sensor_a
    command: python sensor.py --id sensor_a --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      - subrede_esquerda
    depends_on:
      - rabbitmq

  sensor_b:
    build: 
      context: .
      dockerfile: Dockerfile.sensor
    container_name: sensor_b
    command: python sensor.py --id sensor_b --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      - subrede_direita
    depends_on:
      - rabbitmq

  semaforo_1:
    build:
      context: .
      dockerfile: Dockerfile.semaforo
    container_name: semaforo_1
    command: python semaforo.py --id 1 --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      rede_controle:
        ipv4_address: 192.168.140.11
    depends_on:
      - rabbitmq

  semaforo_2:
    build:
      context: .
      dockerfile: Dockerfile.semaforo
    container_name: semaforo_2
    command: python semaforo.py --id 2 --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      rede_controle:
        ipv4_address: 192.168.140.12
    depends_on:
      - rabbitmq

  semaforo_3:
    build:
      context: .
      dockerfile: Dockerfile.semaforo
    container_name: semaforo_3
    command: python semaforo.py --id 3 --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      rede_controle:
        ipv4_address: 192.168.140.13
    depends_on:
      - rabbitmq

  semaforo_4:
    build:
      context: .
      dockerfile: Dockerfile.semaforo
    container_name: semaforo_4
    command: python semaforo.py --id 4 --broker rabbitmq
    cap_add:
      - NET_ADMIN
    networks:
      rede_controle:
        ipv4_address: 192.168.140.14
    depends_on:
      - rabbitmq